<?PHP


$TPGBHS=
"(DESCRIPTION =
(ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = orcl)
)
)";
$conn = ocilogon( "TPGBHS", "TPGBHS",$TPGBHS,"WE8ISO8859P15");

?>