PROCEDURE APPS_UPDATE_STUDENT_DTL(o_status OUT INTEGER,p_STD_ID INTEGER,p_STD_NAME VARCHAR2,p_SCHOOL_NAME VARCHAR2,
                                                  p_SSC_PASS_YEAR VARCHAR2,p_COLLAGE_NAME VARCHAR2,p_HSC_PASS_YEAR VARCHAR2,p_PRESENT_PROFESSION VARCHAR2,
                                                  p_WORK_PLACE_NAME VARCHAR2,p_WORK_PLACE_ADDRESS VARCHAR2,p_SPOUSE_NAME VARCHAR2,p_BABY_NAME VARCHAR2,
                                                  p_EMAIL VARCHAR2,p_PHONE VARCHAR2,p_BLOOD_GROUP VARCHAR2,p_EMERGENCY_PHONE VARCHAR2,p_SCHOOL_DIS VARCHAR2,
                                                  p_SPOUSE_JOB VARCHAR2,p_SPOUSE_BLOOD VARCHAR2,p_BABY_NAME2 VARCHAR2,p_BABY_NAME3 VARCHAR2,p_BABY_NAME4 VARCHAR2
                                                  ,p_BABY_NAME5 VARCHAR2,p_BABY_AGE1 VARCHAR2,p_BABY_AGE2 VARCHAR2,p_BABY_AGE3 VARCHAR2,p_BABY_AGE4 VARCHAR2,
                                                  p_BABY_AGE5 VARCHAR2,p_TOTAL_BABY VARCHAR2,p_NICK_NAME VARCHAR2,p_INVITATION_NAME VARCHAR2,REMARK1 VARCHAR2
                                                  ,p_PHOTO VARCHAR2,p_STATUS VARCHAR);